---
title: "Input/Output"
knitr:
  opts_knit:
    root.dir: "cline"
---

# Input/Output {#sec-command-line-input-output}

In this chapter, we will explore commands that will

- display messages
- print file contents
- sort file contents

| Command | Description |
|:--------|:------------|
| `echo` | Display messages |
| `cat` | Print contents of a file |
| `head` | Prints first ten lines of a file by default |
| `tail` | Prints last ten lines of a file by default |
| `more` | Open a file for interactive reading, scrolling & searching |
| `less` | Open a file for interactive reading, scrolling & searching |
| `sort` | Sort a file in ascending order |

## Display Messages

The `echo` command prints text to the terminal. It can be used for writing or appending messages to a file as well.

| Command | Description |
|:--------|:------------|
| `echo` | Display messages |
| `echo -n` | Print message without trailing new line |
| `echo > file` | Write message to a file |
| `echo >> file` | Append message to a file |
| `echo -e` | Enable interpretation of special characters |

### Print Message

Let us start with a simple example. We will print the text `Action of the Toes` to the terminal. It is the release name for R version 3.6.1.

```{bash}
echo Action of the Toes
```

### Redirect Output

What if we want to redirect the output? Instead of printing the text to the terminal, we want to write it to a file. In such cases, use `>` along with the file name to redirect the output to the file. Keep in mind that `>` will overwrite files. If you want to append to files instead of overwriting, use `>>`.

```{bash}
echo Great Truth > release.txt
```

## Print & Concatenate Files

The `cat` command reads data from files, and outputs their contents. It is the simplest way to display the contents of a file at the command line. It can be used to overwrite or append new content to files as well. `cat` stands for **catenate** and can be used to

- display text files
- copy text files into a new document
- append the contents of a text file to the end of another text file, combining them

| Command | Description |
|:--------|:------------|
| `cat` | Print & concatenate files |
| `cat >` | Concatenate several files into the target file |
| `cat >>` | Append several files into the target file |
| `cat -n` | Number all output lines |

### Print Content

Let us print the content of the `release_names.txt` file (it contains R release names).

```{bash}
cat release_names.txt
```

### Number All Output Lines

If you want to number the output line, use the `-n` option.

```{bash}
cat -n release_names.txt
```

### Concatenate Several Files

To concatenate the contents of several files into a target file, use `>`. In the below example, we concatenate the contents of the files `release_names_18.txt` and `release_names_19.txt` into a single file `release_names_18_19.txt`. In this case we are not printing the contents of the file to the terminal and instead we concatenate the contents from both the files and redirect the output to the target file.

```{bash}
cat release_names_18.txt release_names_19.txt > release_names_18_19.txt
cat release_names_18_19.txt
```

## Head

The `head` command will display the firt 10 lines of a file(s) by default. It can be used to display the first few lines or bytes of a file as well. 

| Command | Description |
|:--------|:------------|
| `head` | Output the first parts of a file |
| `head -n` | Output the first n lines of a file |
| `head -c` | Output the first c bytes of a file |
| `head -n -x` | Output everything but the last x lines of a file |
| `head -c -x` | Output everything but the last x bytes of a file |

### Output the first parts of a file

Let us use `head` to display the first 10 lines of the `release_names.txt` file.

```{bash}
head release_names.txt
```

### Output the first n lines of a file

Using the `n` option, we can specify the number of lines to be displayed. In the below example, we display the first 5 lines.

```{bash}
head -n 5 release_names.txt
```

### Output the first c bytes of a file

The `c` option can be used to display characters or bytes instead of lines. Let us display the first 5 bytes of the `release_names.txt` file.

```{bash}
head -c 5 release_names.txt
```

### Output everything but the last 5 lines of a file

To display the last parts of a file, use `-` while specifying the number of lines. In the below example, we display the last 5 lines of the file.

```{bash}
head -n -5 release_names.txt
```

### Output everything but the last 3 bytes of a file

In this example, we display the last 3 bytes of the file using the `c` option and `-` while specifying the number of bytes.

```{bash}
head -c -3 release_names.txt
```

## Tail

The `tail` command displays the last 10 lines of a file(s) by default. It can be used to display the last few lines or bytes of a file as well. 

| Command | Description |
|:--------|:------------|
| `tail` | Display the last part of a file |
| `tail -n num` | Show the last num lines of a file |
| `tail -n +num` | Show all contents of the file starting from num line |
| `tail -c num` | Show last num bytes of a file |
| `tail -f` | Keep reading file until Ctrl + C |
| `tail -F` | Keep reading file until Ctrl + C; even if the file is rotated |

### Display the last parts of a file

Let us use `tail` to display the last 10 lines of the file.

```{bash}
tail release_names.txt
```

### Display the last 5 lines of a file

As we did in the previous section, use `n` to specify the number of lines to be displayed.

```{bash}
tail -n 5 release_names.txt
```

### Display all contents from line 10

We can use `tail` to display all contents of a file starting from a specific line. In the below example, we display all contents of the file starting from the 10th line using the `n` option and `+` prefix while specifying the number of lines.

```{bash}
tail -n +10 release_names.txt
```

### Display the last 10 bytes of a file

Use the `c` option to display the last 7 bytes of a file.

```{bash}
tail -c 7 release_names.txt
```

## More

The `more` command displays text, one screen at a time. It opens a file for 

- interactive reading
- scrolling
- and searching

Press `space` to scroll down the page, the forward slash (`/`) for searching strings, `n` to go to the next match and `q` to quit. 

| Command | Description |
|:--------|:------------|
| `more` | Open a file for interactive reading, scrolling & searching |
| `space` | Page down |
| `/` | Search for a string; press `n` to go the next match |
| `q` | Quit |

## Less

The `less` command is similar to `more` but offers more features. It allows the
user to scroll up and down, go to the beggining and end of the file, forward and backward search and the ability to go the next and previous match while searching the file.

| Command | Description |
|:--------|:------------|
| `less` | Open a file for interactive reading, scrolling & searching |
| `space` | Page down |
| `b` | Page up |
| `G` | Go to the end of file |
| `g` | Go to the start of file |
| `/` | Forward search |
| `?` | Backward search |
| `n` | Go to next match |
| `N` | Go to previous match |
| `q` | Quit |

## Sort

The `sort` command will sort the contents of text file, line by line. Using additional options, we can

- sort a file in ascending/descending order
- ignore case while sorting
- use numeric order for sorting
- preserve only unique lines while sorting

Using the `sort` command, the contents can be sorted numerically and alphabetically. By default, the rules for sorting are:

- lines starting with a number will appear before lines starting with a letter.
- lines starting with a letter that appears earlier in the alphabet will appear
before lines starting with a letter that appears later in the alphabet.
- lines starting with a lowercase letter will appear before lines starting with the same letter in uppercase.

Using additional options, the rules for sorting can be changed. We list the options in the below table.

| Command | Description |
|:--------|:------------|
| `sort` | Sort lines of text files |
| `sort -r` | Sort a file in descending order |
| `sort --ignore-case` | Ignore case while sorting |
| `sort -n` | Use numeric order for sorting |
| `sort -u` | Preserve only unique lines while sorting |

### Sort 

Let us sort the contents of the `pkg_names.txt` file. It contains names R packages randomly selected from CRAN.

```{bash}
sort pkg_names.txt
```

### Descending Order

Using the `-r` option which stands for `--reverse` the contents of the file can be sorted in descending/reverse order. Let us now sort the contents of the `pkg_names.txt` file in reverse order.

```{bash}
sort -r pkg_names.txt
```

### Ignore case

To ignore case while sorting contents, use the `--ignore-case` option. Time to sort the `pkg_names.txt` file while ignoring case.

```{bash}
sort --ignore-case pkg_names.txt
```

### Numeric Order

To sort numerically, use the `-n` option which stands for `--numeric-sort`. In this example, we will use a different file, `package_names.txt` where the package names are prefixed by random numbers between 1 and 100. 

```{bash}
sort -n package_names.txt
```

### Preserve Only Unique Lines

The `-u` option which stands for `--unique` will preserve only unique lines while sorting the contents of the file. In the below example, we remove all duplicate lines from the `pkg_names.txt` while sorting.

```{bash}
sort -u pkg_names.txt
```

## Word Count

`wc` will print newline, word, and  byte  counts  for  file(s). If more than one file is specified, it will also print total line.
       
### Count words, bytes and lines

```{bash}
wc release_names.txt
```

### Count lines in a file

```{bash}
wc -l release_names.txt
```

### Count words in a file

```{bash}
wc -w release_names.txt
```

### Count characters(bytes) in a file

```{bash}
wc -c release_names.txt
```
